//Variables are containers for storing information
//if e reference nako ang Var Auth mugawas na dayun siya sa
//box container
var author = [
  'Audrey Hepburn',
  'Maya Angelou',
  'Henry Ford',
  'Vince Lombardi',
  'Charles Swindoll',
  'Oprah Winfrey',
  'Ken Blanchard',
  'Jimmy Dean',
  'Theodore Roosevelt',
  'Eleanor Roosevelt',
  'Les Brown',
  'Helen Keller',
  'Napoleon Hill',
  'Mark Twain',
  'Michael Jordan',
  'Albert Einstein',
  'Stephen Covey',
  'Henry Ford',
  'Alice Walker',
  'Amelia Earhart',
  'Andrew Carnegie',
  'Robert Louis Stevenson',
  'Zig Ziglar',
  'Norman Vincent Peale',
  'Josiah Gilbert Holland',
  'William James',
  'Farrah Gray',
  'Dalai Lama',
  'Maya Angelou',
  'Rosa Parks',
  'Vincent van Gogh',
  'Unknown',
  'Albert Einstein',
  'Bob Dylan',
  'Leonardo da Vinci',
  'Booker T. Washington',
  'Erma Bombeck',
  'Will Rogers',
  'Ancient Indian Proverb',
  'Sydney Harris',
  'Confucius',
  'Benjamin Disraeli',
  'John Lennon',
  'Ralph Waldo Emerson',
  'Ronald Reagan',
  'George Addair',
  'Plato',
  'Maya Angelou',
  'Mother Teresa',
  'Plutarch',
];
