var quotes = [
  'Nothing is impossible, the word itself says “I’m possible”!',
  'I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.',
  'Whether you think you can or you think you can’t, you’re right.',
  'Perfection is not attainable, but if we chase perfection we can catch excellence. ',
  'Life is 10 percent what happens to me and 90 percent of how I react to it.',
  'If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.',
  'None of us is as smart as all of us.',
  'I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.',
  'Believe you can and you’re halfway there. ',
  'To handle yourself, use your head; to handle others, use your heart. ',
  'Too many of us are not living our dreams because we are living our fears. ',
  'Alone, we can do so little; together we can do so much. ',
  'Whatever the mind of man can conceive and believe, it can achieve.',
  'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.',
  'I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.',
  'Strive not to be a success, but rather to be of value. ',
  'I am not a product of my circumstances. I am a product of my decisions. ',
  'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.',
  'The most common way people give up their power is by thinking they don’t have any.',
  'The most difficult thing is the decision to act, the rest is merely tenacity. ',
  'Teamwork is the ability to work together toward a common vision, the ability to direct individual accomplishments toward organizational objectives. It is the fuel that allows common people to attain uncommon results. ',
  'Don’t judge each day by the harvest you reap but by the seeds that you plant.',
  'The real opportunity for success lies within the person and not in the job.',
  'Change your thoughts and you change your world.',
  'There is no royal road to anything. One thing at a time, all things in succession. That which grows fast, withers as rapidly. That which grows slowly, endures.',
  'Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. ',
  'Build your own dreams, or someone else will hire you to build theirs.',
  'Remember that not getting what you want is sometimes a wonderful stroke of luck.',
  'You can’t use up creativity. The more you use, the more you have.',
  'I have learned over the years that when one’s mind is made up, this diminishes fear.',
  'I would rather die of passion than of boredom. ',
  'A truly rich man is one whose children run into his arms when his hands are empty. ',
  'A person who never made a mistake never tried anything new. ',
  'What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.',
  'I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. ',
  'If you want to lift yourself up, lift up someone else. ',
  'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.',
  'The quickest way to double your money is to fold it over and put it back in your pocket.',
  'Certain things catch your eye, but pursue only those that capture the heart. ',
  'When I hear somebody sigh, ‘Life is hard,’ I am always tempted to ask, ‘Compared to what?’”',
  'Everything has beauty, but not everyone can see.',
  'Nurture your mind with great thoughts. To believe in the heroic makes heroes. ',
  'When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down “happy”. They told me I didn’t understand the assignment, and I told them they didn’t understand life.',
  'The only person you are destined to become is the person you decide to be. ',
  'We can’t help everyone, but everyone can help someone.',
  'Everything you’ve ever wanted is on the other side of fear. ',
  'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.',
  'Nothing will work unless you do.',
  'I alone cannot change the world, but I can cast a stone across the water to create many ripples.',
  'What we achieve inwardly will change outer reality.',
];
